// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_append from "./routes/api/append.ts";
import * as $api_auth from "./routes/api/auth.ts";
import * as $api_markdown from "./routes/api/markdown.ts";
import * as $api_process from "./routes/api/process.ts";
import * as $api_share_shareId_ from "./routes/api/share/[shareId].ts";
import * as $api_share_create from "./routes/api/share/create.ts";
import * as $index from "./routes/index.tsx";
import * as $shared_shareId_ from "./routes/shared/[shareId].tsx";
import * as $shared_index from "./routes/shared/index.tsx";
import * as $ArcDiagramViz from "./islands/ArcDiagramViz.tsx";
import * as $AudioRecorder from "./islands/AudioRecorder.tsx";
import * as $AudioVisualizer from "./islands/AudioVisualizer.tsx";
import * as $ConversationList from "./islands/ConversationList.tsx";
import * as $DashboardIsland from "./islands/DashboardIsland.tsx";
import * as $EmojimapViz from "./islands/EmojimapViz.tsx";
import * as $ForceDirectedGraph from "./islands/ForceDirectedGraph.tsx";
import * as $HomeIsland from "./islands/HomeIsland.tsx";
import * as $MarkdownMakerDrawer from "./islands/MarkdownMakerDrawer.tsx";
import * as $MobileHistoryMenu from "./islands/MobileHistoryMenu.tsx";
import * as $ShareButton from "./islands/ShareButton.tsx";
import * as $SharedConversationLoader from "./islands/SharedConversationLoader.tsx";
import * as $UploadIsland from "./islands/UploadIsland.tsx";
import * as $VisualizationSelector from "./islands/VisualizationSelector.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/append.ts": $api_append,
    "./routes/api/auth.ts": $api_auth,
    "./routes/api/markdown.ts": $api_markdown,
    "./routes/api/process.ts": $api_process,
    "./routes/api/share/[shareId].ts": $api_share_shareId_,
    "./routes/api/share/create.ts": $api_share_create,
    "./routes/index.tsx": $index,
    "./routes/shared/[shareId].tsx": $shared_shareId_,
    "./routes/shared/index.tsx": $shared_index,
  },
  islands: {
    "./islands/ArcDiagramViz.tsx": $ArcDiagramViz,
    "./islands/AudioRecorder.tsx": $AudioRecorder,
    "./islands/AudioVisualizer.tsx": $AudioVisualizer,
    "./islands/ConversationList.tsx": $ConversationList,
    "./islands/DashboardIsland.tsx": $DashboardIsland,
    "./islands/EmojimapViz.tsx": $EmojimapViz,
    "./islands/ForceDirectedGraph.tsx": $ForceDirectedGraph,
    "./islands/HomeIsland.tsx": $HomeIsland,
    "./islands/MarkdownMakerDrawer.tsx": $MarkdownMakerDrawer,
    "./islands/MobileHistoryMenu.tsx": $MobileHistoryMenu,
    "./islands/ShareButton.tsx": $ShareButton,
    "./islands/SharedConversationLoader.tsx": $SharedConversationLoader,
    "./islands/UploadIsland.tsx": $UploadIsland,
    "./islands/VisualizationSelector.tsx": $VisualizationSelector,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
