// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_append from "./routes/api/append.ts";
import * as $api_ask from "./routes/api/ask.ts";
import * as $api_auth from "./routes/api/auth.ts";
import * as $api_live_analyze from "./routes/api/live/analyze.ts";
import * as $api_live_chunk from "./routes/api/live/chunk.ts";
import * as $api_live_create from "./routes/api/live/create.ts";
import * as $api_live_voice_token from "./routes/api/live/voice-token.ts";
import * as $api_live_whiteboard_agent from "./routes/api/live/whiteboard-agent.ts";
import * as $api_markdown from "./routes/api/markdown.ts";
import * as $api_process from "./routes/api/process.ts";
import * as $api_share_shareId_ from "./routes/api/share/[shareId].ts";
import * as $api_share_create from "./routes/api/share/create.ts";
import * as $dev_colors from "./routes/dev/colors.tsx";
import * as $dev_nodemap from "./routes/dev/nodemap.tsx";
import * as $index from "./routes/index.tsx";
import * as $live_roomId_ from "./routes/live/[roomId].tsx";
import * as $shared_shareId_ from "./routes/shared/[shareId].tsx";
import * as $shared_index from "./routes/shared/index.tsx";
import * as $AudioRecorder from "./islands/AudioRecorder.tsx";
import * as $AudioVisualizer from "./islands/AudioVisualizer.tsx";
import * as $AuthModalIsland from "./islands/AuthModalIsland.tsx";
import * as $ColorLabIsland from "./islands/ColorLabIsland.tsx";
import * as $DashboardIsland from "./islands/DashboardIsland.tsx";
import * as $EmojimapViz from "./islands/EmojimapViz.tsx";
import * as $FlipCard from "./islands/FlipCard.tsx";
import * as $ForceDirectedGraph from "./islands/ForceDirectedGraph.tsx";
import * as $GoLiveButton from "./islands/GoLiveButton.tsx";
import * as $HomeIsland from "./islands/HomeIsland.tsx";
import * as $MarkdownMakerDrawer from "./islands/MarkdownMakerDrawer.tsx";
import * as $MobileHistoryMenu from "./islands/MobileHistoryMenu.tsx";
import * as $ModuleRack from "./islands/ModuleRack.tsx";
import * as $NodemapTestIsland from "./islands/NodemapTestIsland.tsx";
import * as $ReaderModal from "./islands/ReaderModal.tsx";
import * as $ShareButton from "./islands/ShareButton.tsx";
import * as $SharedConversationLoader from "./islands/SharedConversationLoader.tsx";
import * as $SharedWhiteboard from "./islands/SharedWhiteboard.tsx";
import * as $SoundToggle from "./islands/SoundToggle.tsx";
import * as $ThemeSwitcher from "./islands/ThemeSwitcher.tsx";
import * as $TopicVisualizationsCard from "./islands/TopicVisualizationsCard.tsx";
import * as $UploadIsland from "./islands/UploadIsland.tsx";
import * as $VisualizationSelector from "./islands/VisualizationSelector.tsx";
import * as $VoicePanel from "./islands/VoicePanel.tsx";
import * as $modules_BishopModule from "./islands/modules/BishopModule.tsx";
import * as $modules_NotesModule from "./islands/modules/NotesModule.tsx";
import * as $modules_SoundModule from "./islands/modules/SoundModule.tsx";
import * as $modules_TakesModule from "./islands/modules/TakesModule.tsx";
import * as $modules_moduleRegistry from "./islands/modules/moduleRegistry.ts";
import * as $useRecorder from "./islands/useRecorder.ts";
import * as $vizRegistry from "./islands/vizRegistry.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/append.ts": $api_append,
    "./routes/api/ask.ts": $api_ask,
    "./routes/api/auth.ts": $api_auth,
    "./routes/api/live/analyze.ts": $api_live_analyze,
    "./routes/api/live/chunk.ts": $api_live_chunk,
    "./routes/api/live/create.ts": $api_live_create,
    "./routes/api/live/voice-token.ts": $api_live_voice_token,
    "./routes/api/live/whiteboard-agent.ts": $api_live_whiteboard_agent,
    "./routes/api/markdown.ts": $api_markdown,
    "./routes/api/process.ts": $api_process,
    "./routes/api/share/[shareId].ts": $api_share_shareId_,
    "./routes/api/share/create.ts": $api_share_create,
    "./routes/dev/colors.tsx": $dev_colors,
    "./routes/dev/nodemap.tsx": $dev_nodemap,
    "./routes/index.tsx": $index,
    "./routes/live/[roomId].tsx": $live_roomId_,
    "./routes/shared/[shareId].tsx": $shared_shareId_,
    "./routes/shared/index.tsx": $shared_index,
  },
  islands: {
    "./islands/AudioRecorder.tsx": $AudioRecorder,
    "./islands/AudioVisualizer.tsx": $AudioVisualizer,
    "./islands/AuthModalIsland.tsx": $AuthModalIsland,
    "./islands/ColorLabIsland.tsx": $ColorLabIsland,
    "./islands/DashboardIsland.tsx": $DashboardIsland,
    "./islands/EmojimapViz.tsx": $EmojimapViz,
    "./islands/FlipCard.tsx": $FlipCard,
    "./islands/ForceDirectedGraph.tsx": $ForceDirectedGraph,
    "./islands/GoLiveButton.tsx": $GoLiveButton,
    "./islands/HomeIsland.tsx": $HomeIsland,
    "./islands/MarkdownMakerDrawer.tsx": $MarkdownMakerDrawer,
    "./islands/MobileHistoryMenu.tsx": $MobileHistoryMenu,
    "./islands/ModuleRack.tsx": $ModuleRack,
    "./islands/NodemapTestIsland.tsx": $NodemapTestIsland,
    "./islands/ReaderModal.tsx": $ReaderModal,
    "./islands/ShareButton.tsx": $ShareButton,
    "./islands/SharedConversationLoader.tsx": $SharedConversationLoader,
    "./islands/SharedWhiteboard.tsx": $SharedWhiteboard,
    "./islands/SoundToggle.tsx": $SoundToggle,
    "./islands/ThemeSwitcher.tsx": $ThemeSwitcher,
    "./islands/TopicVisualizationsCard.tsx": $TopicVisualizationsCard,
    "./islands/UploadIsland.tsx": $UploadIsland,
    "./islands/VisualizationSelector.tsx": $VisualizationSelector,
    "./islands/VoicePanel.tsx": $VoicePanel,
    "./islands/modules/BishopModule.tsx": $modules_BishopModule,
    "./islands/modules/NotesModule.tsx": $modules_NotesModule,
    "./islands/modules/SoundModule.tsx": $modules_SoundModule,
    "./islands/modules/TakesModule.tsx": $modules_TakesModule,
    "./islands/modules/moduleRegistry.ts": $modules_moduleRegistry,
    "./islands/useRecorder.ts": $useRecorder,
    "./islands/vizRegistry.ts": $vizRegistry,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
