import { type PageProps } from "$fresh/server.ts";
import { asset } from "$fresh/runtime.ts";

export default function App({ Component }: PageProps) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <script
          defer
          src="https://fleetcount.pibulus.deno.net/beacon.js"
          data-site="promapper.app"
        >
        </script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* Primary Meta Tags */}
        <title>ProMapper - Living project maps from messy conversations</title>
        <meta
          name="title"
          content="ProMapper - Living project maps from messy conversations"
        />
        <meta
          name="description"
          content="ProMapper turns voice notes, meetings, research, scenes, and written rants into project memory: transcript, summary, actions, topic map, docs, and sharing."
        />

        {/* Canonical (matches og:url; avoids dup-URL from share query params) */}
        <link rel="canonical" href="https://promapper.app/" />

        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://promapper.app/" />
        <meta
          property="og:title"
          content="ProMapper - Living project maps from messy conversations"
        />
        <meta
          property="og:description"
          content="A friendly way to turn ongoing conversations and notes into transcripts, summaries, actions, topic maps, docs, and shared context."
        />
        {
          /* ABSOLUTE image URL — link scrapers (iMessage, WhatsApp, Slack)
            silently drop relative og:image paths, so the card showed no
            thumbnail. Width/height let them render before downloading. */
        }
        <meta
          property="og:image"
          content="https://promapper.app/og-image.png"
        />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta
          property="og:image:alt"
          content="ProMapper — project maps from messy conversations"
        />

        {/* Twitter */}
        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://promapper.app/"
        />
        <meta
          property="twitter:title"
          content="ProMapper - Living project maps from messy conversations"
        />
        <meta
          property="twitter:description"
          content="A friendly way to turn ongoing conversations and notes into transcripts, summaries, actions, topic maps, docs, and shared context."
        />
        <meta
          property="twitter:image"
          content="https://promapper.app/og-image.png"
        />

        {/* Favicon */}
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />

        {/* Theme Color */}
        <meta name="theme-color" content="#ffb98a" />

        {
          /* Inter (headers) + IBM Plex Mono (body) — as <link>s so the font
            fetch runs parallel to the stylesheet (the old @import inside
            styles.css serialized it behind the whole CSS download). */
        }
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap"
        />

        {
          /* Icons — a self-hosted FontAwesome subset of the 69 icons this app
             actually uses. The cdnjs stylesheet was 103KB and pulled a 156KB
             solid font for all of them; this pair is ~10KB and costs no
             third-party origin. Regenerate with scratch/fa-subset.py after
             adding a NEW fa-* icon, or its glyph renders as a blank box. */
        }
        <link
          rel="preload"
          as="font"
          type="font/woff2"
          href="/fonts/fa-solid-900.woff2"
          crossOrigin="anonymous"
        />
        <link rel="stylesheet" href={asset("/fa-subset.css")} />

        {
          /* Styles — styles.build.css is the Tailwind-compiled output of
            static/styles.css, generated by `deno task build:css`. It is built
            ahead of time and committed because the Fresh tailwind plugin does
            not run on Deno Deploy. Edit static/styles.css, never this output.

            asset() appends Fresh's build id, so a CSS deploy lands instantly.
            Bare hrefs were served unversioned behind a 4h CDN TTL (verified
            Aug 20: cf-cache-status HIT, age 5151, on a deploy minutes old) —
            every style fix was invisible in production for hours, which is
            how a local build and the live site could disagree all afternoon. */
        }
        <link rel="stylesheet" href={asset("/styles.build.css")} />

        {
          /* FOUC prevention: apply saved theme CSS vars before first paint.
            Reads localStorage["promapper-theme"], looks up a minimal inline
            map of name → vars, and sets them on :root.
            Zero imports — intentionally self-contained. */
        }
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{
var saved=localStorage.getItem("promapper-theme");
if(!saved)return;
var parsed=JSON.parse(saved);
if(!parsed||parsed.name!=="SHUFFLE")return;
if(parsed.v!==13||!parsed.custom||!parsed.custom.vars)return;
var cv=parsed.custom.vars;
for(var ck in cv){document.documentElement.style.setProperty(ck,cv[ck]);}
}catch(e){}})();`,
          }}
        />

        {
          /* Resize guard: stamps .is-resizing on <html> while the window is
            actively being resized so CSS can switch transitions off (see
            styles.css) — without it, breakpoint flips animate mid-drag and
            the layout "chases" the cursor. Self-contained on purpose. */
        }
        <script
          dangerouslySetInnerHTML={{
            __html:
              `(function(){var t;addEventListener("resize",function(){document.documentElement.classList.add("is-resizing");clearTimeout(t);t=setTimeout(function(){document.documentElement.classList.remove("is-resizing")},150)})})();`,
          }}
        />
        {
          /* MISSING THE DROPZONE MUST NOT NAVIGATE AWAY.
            The Magpie shelf and the upload box accept dropped files, which
            teaches people this app eats files — and then a drop that lands
            40px wide, on the map or the gap between cards, hits the BROWSER's
            default handler and replaces the whole board with a preview of
            their PDF. Autosave makes it recoverable; it still reads as a
            crash. Anything outside a real dropzone is swallowed instead.
            Inline and listener-based so it covers the page from first paint,
            including routes with no island mounted yet. */
        }
        <script
          dangerouslySetInnerHTML={{
            __html:
              `(function(){function outside(e){var t=e.target;return !(t&&t.closest&&t.closest("[data-dropzone]"))}` +
              `["dragover","drop"].forEach(function(n){addEventListener(n,function(e){if(outside(e))e.preventDefault()},false)})})();`,
          }}
        />
      </head>
      <body>
        <div class="scroll-progress" aria-hidden="true"></div>
        <Component />
      </body>
    </html>
  );
}
