import { type PageProps } from "$fresh/server.ts";

export default function App({ Component }: PageProps) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* Primary Meta Tags */}
        <title>ProMapper - Living project maps from messy conversations</title>
        <meta
          name="title"
          content="ProMapper - Living project maps from messy conversations"
        />
        <meta
          name="description"
          content="ProMapper turns voice notes, meetings, research, scenes, and written rants into project memory: transcript, summary, actions, topic map, docs, and sharing."
        />

        {/* Canonical (matches og:url; avoids dup-URL from share query params) */}
        <link rel="canonical" href="https://promapper.app/" />

        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://promapper.app/" />
        <meta
          property="og:title"
          content="ProMapper - Living project maps from messy conversations"
        />
        <meta
          property="og:description"
          content="A friendly way to turn ongoing conversations and notes into transcripts, summaries, actions, topic maps, docs, and shared context."
        />
        {
          /* ABSOLUTE image URL — link scrapers (iMessage, WhatsApp, Slack)
            silently drop relative og:image paths, so the card showed no
            thumbnail. Width/height let them render before downloading. */
        }
        <meta
          property="og:image"
          content="https://promapper.app/og-image.png"
        />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta
          property="og:image:alt"
          content="ProMapper — project maps from messy conversations"
        />

        {/* Twitter */}
        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://promapper.app/"
        />
        <meta
          property="twitter:title"
          content="ProMapper - Living project maps from messy conversations"
        />
        <meta
          property="twitter:description"
          content="A friendly way to turn ongoing conversations and notes into transcripts, summaries, actions, topic maps, docs, and shared context."
        />
        <meta
          property="twitter:image"
          content="https://promapper.app/og-image.png"
        />

        {/* Favicon */}
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />

        {/* Theme Color */}
        <meta name="theme-color" content="#FFE5EC" />

        {/* Icons — FontAwesome (the whole app uses `fa fa-*` icons in chrome). */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          crossOrigin="anonymous"
          referrerpolicy="no-referrer"
        />

        {/* Styles — styles.build.css is the Tailwind-compiled output of
            static/styles.css, generated by `deno task build:css`. It is built
            ahead of time and committed because the Fresh tailwind plugin does
            not run on Deno Deploy. Edit static/styles.css, never this output. */}
        <link rel="stylesheet" href="/styles.build.css" />

        {
          /* FOUC prevention: apply saved theme CSS vars before first paint.
            Reads localStorage["promapper-theme"], looks up a minimal inline
            map of name → vars, and sets them on :root.
            Zero imports — intentionally self-contained. */
        }
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{
var saved=localStorage.getItem("promapper-theme");
if(!saved)return;
var parsed=JSON.parse(saved);
var name=parsed&&parsed.name;
if(!name)return;
if(name==="SHUFFLE"){
if(parsed.v!==8||!parsed.custom||!parsed.custom.vars)return;
var cv=parsed.custom.vars;
for(var ck in cv){document.documentElement.style.setProperty(ck,cv[ck]);}
return;}
var themes={
  "DAYBREAK":{
    "--color-base":"linear-gradient(135deg,#ffe2cf 0%,#ffd0bd 100%)",
    "--color-base-solid":"#ffe2cf",
    "--color-base-gradient":"linear-gradient(135deg,#ffe2cf 0%,#ffd0bd 100%)",
    "--color-secondary":"rgba(255,250,243,0.62)",
    "--color-accent":"#4a7bc9",
    "--color-text":"#232a3a",
    "--color-text-secondary":"#6b7386",
    "--color-border":"rgba(35,42,58,0.1)",
    "--shadow-soft":"0 4px 12px rgba(74,123,201,0.14)",
    
    "--gradient-bg":"radial-gradient(circle at 18% 0%,rgba(255,166,128,0.85),transparent 52%),radial-gradient(circle at 82% 6%,rgba(255,143,112,0.7),transparent 52%),linear-gradient(168deg,#ffb28c 0%,#ffe0c9 38%,#fff4e8 78%)"
  },
  "BUBBLEGUM":{
    "--color-base":"linear-gradient(135deg,#ffd9e5 0%,#ffcbd7 100%)",
    "--color-base-solid":"#ffd9e5",
    "--color-base-gradient":"linear-gradient(135deg,#ffd9e5 0%,#ffcbd7 100%)",
    "--color-secondary":"rgba(255,250,243,0.62)",
    "--color-accent":"#ff2e88",
    "--color-text":"#2b2430",
    "--color-text-secondary":"#8a7e88",
    "--color-border":"rgba(43,36,48,0.1)",
    "--shadow-soft":"0 4px 12px rgba(255,77,151,0.12)",
    
    "--gradient-bg":"radial-gradient(circle at 18% 0%,rgba(255,185,184,0.85),transparent 52%),radial-gradient(circle at 82% 6%,rgba(255,186,215,0.7),transparent 52%),linear-gradient(168deg,#ffbcc7 0%,#ffddeb 38%,#fff4e8 78%)"
  },
  "SKY":{
    "--color-base":"linear-gradient(135deg,#c2f2f9 0%,#adeaf9 100%)",
    "--color-base-solid":"#c2f2f9",
    "--color-base-gradient":"linear-gradient(135deg,#c2f2f9 0%,#adeaf9 100%)",
    "--color-secondary":"rgba(255,250,243,0.65)",
    "--color-accent":"#0095ff",
    "--color-text":"#1f3344",
    "--color-text-secondary":"#6f8597",
    "--color-border":"rgba(31,51,68,0.1)",
    "--shadow-soft":"0 4px 12px rgba(10,166,255,0.12)",
    
    "--gradient-bg":"radial-gradient(circle at 18% 0%,rgba(157,238,247,0.85),transparent 52%),radial-gradient(circle at 82% 6%,rgba(176,227,255,0.7),transparent 52%),linear-gradient(168deg,#a0edfb 0%,#cff2ff 38%,#fff4e8 78%)"
  },
  "GRAPE":{
    "--color-base":"linear-gradient(135deg,#fdd7f3 0%,#f1ccf7 100%)",
    "--color-base-solid":"#fdd7f3",
    "--color-base-gradient":"linear-gradient(135deg,#fdd7f3 0%,#f1ccf7 100%)",
    "--color-secondary":"rgba(255,250,243,0.65)",
    "--color-accent":"#8335ff",
    "--color-text":"#312a45",
    "--color-text-secondary":"#807a96",
    "--color-border":"rgba(49,42,69,0.1)",
    "--shadow-soft":"0 4px 12px rgba(131,53,255,0.12)",
    
    "--gradient-bg":"radial-gradient(circle at 18% 0%,rgba(251,181,220,0.85),transparent 52%),radial-gradient(circle at 82% 6%,rgba(225,190,247,0.7),transparent 52%),linear-gradient(168deg,#f3bced 0%,#f5deff 38%,#fff4e8 78%)"
  },
  "LIME":{
    "--color-base":"linear-gradient(135deg,#c3f3ec 0%,#acece9 100%)",
    "--color-base-solid":"#c3f3ec",
    "--color-base-gradient":"linear-gradient(135deg,#c3f3ec 0%,#acece9 100%)",
    "--color-secondary":"rgba(255,250,243,0.65)",
    "--color-accent":"#0fb255",
    "--color-text":"#1f3a2b",
    "--color-text-secondary":"#6f8c7c",
    "--color-border":"rgba(31,58,43,0.1)",
    "--shadow-soft":"0 4px 12px rgba(16,181,80,0.12)",
    
    "--gradient-bg":"radial-gradient(circle at 18% 0%,rgba(162,240,224,0.85),transparent 52%),radial-gradient(circle at 82% 6%,rgba(162,237,244,0.7),transparent 52%),linear-gradient(168deg,#a0efe9 0%,#ccf5f4 38%,#fff4e8 78%)"
  },
  "GOLD":{
    "--color-base":"linear-gradient(135deg,#ffdec2 0%,#fdd2a6 100%)",
    "--color-base-solid":"#ffdec2",
    "--color-base-gradient":"linear-gradient(135deg,#ffdec2 0%,#fdd2a6 100%)",
    "--color-secondary":"rgba(255,250,243,0.65)",
    "--color-accent":"#f5a300","--accent-strong":"#a06a00",
    "--color-text":"#3a3016",
    "--color-text-secondary":"#8a7b54",
    "--color-border":"rgba(58,48,22,0.1)",
    "--shadow-soft":"0 4px 12px rgba(245,179,0,0.14)",
    
    "--gradient-bg":"radial-gradient(circle at 18% 0%,rgba(255,195,149,0.85),transparent 52%),radial-gradient(circle at 82% 6%,rgba(250,203,141,0.7),transparent 52%),linear-gradient(168deg,#ffc895 0%,#fee3c5 38%,#fff4e8 78%)"
  }
};
var vars=themes[name];
if(!vars)return;
var root=document.documentElement;
Object.keys(vars).forEach(function(k){root.style.setProperty(k,vars[k]);});
}catch(e){}})();`,
          }}
        />
      </head>
      <body>
        <div class="scroll-progress" aria-hidden="true"></div>
        <Component />
      </body>
    </html>
  );
}
